<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>CoreLayers</RootNamespace>
        <AssemblyName>core-layers</AssemblyName>
        <RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
        <Configurations>Debug;Release</Configurations>
        <DebugType>embedded</DebugType>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="$(NF_ROOT)\Lib\Neon.BuildInfo\AssemblyAttributes.cs" Link="Properties\AssemblyAttributes.cs" />
        <Compile Include="$(NF_ROOT)\Lib\Neon.BuildInfo\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Neon.BuildInfo\Neon.BuildInfo.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Properties\PublishProfiles\" />
    </ItemGroup>

</Project>
