namespace Microsoft.Virtualization.Client.Management.Clustering;

internal sealed class MSClusterVMConfigurationResourceView : MSClusterVMOrConfigurationResourceView, IMSClusterVMConfigurationResource, IMSClusterVMOrConfigurationResource, IMSClusterResource, IMSClusterResourceBase, IVirtualizationManagementObject
{
}
