namespace Microsoft.Virtualization.Client.Management.Clustering;

internal sealed class MSClusterVMResourceView : MSClusterVMOrConfigurationResourceView, IMSClusterVMResource, IMSClusterVMOrConfigurationResource, IMSClusterResource, IMSClusterResourceBase, IVirtualizationManagementObject
{
}
