<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <OutputType>Library</OutputType>
        <Configurations>Debug;Release</Configurations>
        <Description>Kubernetes SDK extensions and helpers.</Description>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageProjectUrl>https://docs.neonforge.com/docs/operator-sdk</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nforgeio/operator-sdk</RepositoryUrl>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <IsPackable>true</IsPackable>
        <RepositoryType>git</RepositoryType>
        <PackageTags>kubernetes k8s</PackageTags>
        <PackageReleaseNotes>https://github.com/nforgeio/operator-sdk/releases</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <NoWarn>$(NoWarn);CS8632</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KubernetesClient.Classic" Version="17.0.14" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="$(DotNetVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(DotNetVersion)" />
        <PackageReference Include="prometheus-net" Version="8.2.1" />
        <PackageReference Include="System.Text.Json" Version="$(DotNetVersion)" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\nuget-icon.png" Pack="true" PackagePath="" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Neon.Common\Neon.Common.csproj" />
    </ItemGroup>

</Project>
