namespace Microsoft.Virtualization.Client.Management;

internal class InstalledEthernetSwitchExtensionView : EthernetSwitchExtensionBaseView, IInstalledEthernetSwitchExtension, IEthernetSwitchExtensionBase, IVirtualizationManagementObject
{
}
