<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>Neon.Common</RootNamespace>
        <Description>Additional classes used by other NeonSDK packages as well as NEONFORGE applications</Description>
        <PackageReleaseNotes>https://github.com/nforgeio/neonSDK/releases</PackageReleaseNotes>
        <IsPackable>true</IsPackable>
        <PackageProjectUrl>https://github.com/nforgeio/neonSDK/blob/master/Lib/Neon.Common.Extensions/README.md</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/nforgeio/neonSDK</RepositoryUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Configurations>Debug;Release</Configurations>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <PackageTags>utility classes</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\Neon.BuildInfo\AssemblyAttributes.cs" Link="Properties\AssemblyAttributes.cs" />
        <Compile Include="..\Neon.BuildInfo\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" />
        <PackageReference Include="Microsoft.Win32.Registry" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="Quartz" />
        <PackageReference Include="SharpZipLib.NETStandard" />
        <PackageReference Include="System.Diagnostics.Contracts" />
        <PackageReference Include="System.Diagnostics.Process" />
        <PackageReference Include="System.IO.FileSystem.AccessControl" />
        <PackageReference Include="System.Net.Http" />
        <PackageReference Include="System.Runtime" />
        <PackageReference Include="System.Runtime.Serialization.Primitives" />
        <PackageReference Include="System.Security.AccessControl" />
        <PackageReference Include="System.Threading.Thread" />
        <PackageReference Include="System.ValueTuple" />
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\nuget-icon.png" Pack="true" PackagePath="" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Neon.BuildInfo\Neon.BuildInfo.csproj" />
        <ProjectReference Include="..\Neon.Common\Neon.Common.csproj" />
    </ItemGroup>

</Project>
