namespace Neon.Blazor.Analyzers
{
    internal static class Constants
    {
        public const string AutoGeneratedHeader = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NeonFORGE Blazor SDK.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";
        public const string ObjectTypeString = "object";
        public const string StringTypeString = "string";
        public const string BooleanTypeString = "boolean";
        public const string IntegerTypeString = "integer";
        public const string NumberTypeString = "number";
        public const string ArrayTypeString = "array";
        public const string Int32TypeString = "int32";
        public const string Int64TypeString = "int64";
        public const string FloatTypeString = "float";
        public const string DoubleTypeString = "double";
        public const string DateTimeTypeString = "date-time";
    }
}
