<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TestECharts</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lib\Neon.Blazor\Neon.Blazor.csproj" />
    <ProjectReference Include="..\..\Lib\Neon.ECharts\Neon.ECharts.csproj" />
  </ItemGroup>

</Project>
